### ISSUE TITLE
Dryya 

### ISSUE THREAD

**Issue by MekoMansy0** [PaleCourt/PaleCourt#75] opened 2024-08-26 02:52 UTC
https://github.com/user-attachments/assets/89371129-7685-4001-9237-b762be8b783d

Whenever I try to load into the Dryya fight/area, it instantly kicks me out of the dream realm. I've tried downloading the mod but it did not work. I've already done 2 of the boss fights and I am hoping to finish the other two, so hopefully this can get fixed soon. I've attached a video of the problem occuring.

**Comment by K1ngC001** [comment] 2024-09-01 21:01
same thing is happening to me. not sure what's causing it. Could you share the mod list to see what's in common?

**Comment by JoshDa777** [comment] 2024-10-26 23:24
I can only think that it could be a bug in the animations so I suggest trying it without the mods that change the animations like Qol's

**Comment by SFGrenade** [comment] 2024-10-27 00:09
duplicate of https://github.com/PaleCourt/PaleCourt/issues/62, check workaround there

**Closed by SFGrenade** 2024-10-27 00:09 UTC
