### ISSUE TITLE
Dryya boss bug.

### ISSUE THREAD

**Issue by Tindarushound** [PaleCourt/PaleCourt#64] opened 2024-01-24 11:55 UTC
https://github.com/PaleCourt/PaleCourt/assets/157308159/8aec016c-035e-4bf7-9b17-19c7cb85f3a0

**Comment by Tindarushound** [comment] 2024-01-24 11:59
Restart the game after saving it.
The mod has not been reinstalled yet (for fear that the talisman records of other mods will be lost).
Note: I am a Chinese speaker, please forgive me if there are any translation grammatical problems.

**Comment by JoshDa777** [comment] 2024-10-26 23:24
I can only think that it could be a bug in the animations so I suggest trying it without the mods that change the animations like Qol's

**Comment by SFGrenade** [comment] 2024-10-27 00:09
duplicate of https://github.com/PaleCourt/PaleCourt/issues/62, check the last message there

**Closed by SFGrenade** 2024-10-27 00:09 UTC
